In [2]:
import numpy as np

In [3]:
# cria uma matriz unidimensional
mt = np.array([12, 34, 26, 10, 10])
print(mt)
print(type(np))

[12 34 26 10 10]
<class 'module'>


In [4]:
# criando um array com um tipos específicos
mtfloat = np.array([1, 2, 3], dtype= np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype= np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# mudar o tipo do array
mtnew = np.array([1.4, 2.6, 3.77, 4.9999999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[1.4       2.6       3.77      4.9999999]
[1 2 3 4]


In [6]:
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
# elemento bidimensional
mt7 = np.array([[7, 2, 23], [12, 27, 35], [15, 18, 19]])
print(mt7)

[[ 7  2 23]
 [12 27 35]
 [15 18 19]]


In [8]:
# criando array que não vai ser inicializado
vazio = np.empty([3, 2], dtype= int)
print(vazio)
print('-----')
# criando matriz 4x3 com valores 0
zeros = np.zeros([4, 3])
print(zeros)
print('-----')
# com valores 1
um = np.ones([5, 7])
print(um)
print('-----')
# matriz quadrada com diagonal com valores 1 e os outros 0
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-----
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# gerando valores aleatórios
# valores aleatório entre 1 e 0
ale = np.random.random((5))
print(ale)
print('-------')
# valores aleatórios com dist. normal, contendo número negativos
ale2 = np.random.randn((5))
print(ale2)
print('-----')
# valores alea. em 3x4
ale3 = np.random.random((3, 4))
print(ale3)


[0.99421519 0.19346196 0.81497027 0.00480379 0.9032742 ]
-------
[ 1.25611015 -2.3180095  -0.6067848   0.4523383   0.4574361 ]
-----
[[0.35528126 0.83679415 0.76200404 0.26364365]
 [0.06665868 0.96385195 0.91997981 0.67623559]
 [0.40599447 0.37090465 0.57913067 0.06907103]]


In [12]:
# outra forma de gerar número aleatórios
# usando uma semente
gnr = np.random.default_rng(1)
ale4 = gnr.random(3)
print(ale4)
print('----')
# gerando inteiros
ale5 = gnr.integers(10, size= (3,4)) # número inteiros até 10, com a matriz de 3x4
print(ale5)


[0.51182162 0.9504637  0.14415961]
----
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [14]:
# removendo repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)


[11 12 13 14 15 16 17 18 19 20]


In [15]:
# alguns usos de funções
k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
print(k)
print('---')
print(k[0][1])
print('---')
print(k.shape) # mostra as dimensões da matriz

[[17 22 43]
 [27 25 14]
 [15 24 32]]
---
22
---
(3, 3)


In [17]:
# funções matemáticas
print(k.max()) # máximo
print(k.min()) # mínimo
print(k.sum()) # soma
print(k.mean()) # média
print(k.std()) # desvio padrão
print(np.sqrt(k)) # raiz quadrada
print(np.exp(k)) # exponencial

43
14
219
24.333333333333332
8.615231988880057
[[4.12310563 4.69041576 6.55743852]
 [5.19615242 5.         3.74165739]
 [3.87298335 4.89897949 5.65685425]]
[[2.41549528e+07 3.58491285e+09 4.72783947e+18]
 [5.32048241e+11 7.20048993e+10 1.20260428e+06]
 [3.26901737e+06 2.64891221e+10 7.89629602e+13]]


In [19]:
# extraindo elementos
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1]) # mostra o elento na posição 2
print(m[0:2]) # mostra os elentos a partir da primeira posição, com dois elementos
print(m[1:]) # mostra do elemento 2 até o fim
print(m[-3:]) # mostra da antepenúltima posição até a o final

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [20]:
# extração de linhas e colunas
l = np.array([[5, 6], [6, 1], [7, 4]])
print(l)
print('---')
l_linha_1 = l[0, :] # primeira linha e todas as colunas. # a mesma lógica pode ser seguida para outras linhas
print(l_linha_1)
print('---')
l_coluna_1 = l[:, 0] #todas e linhas e a primeira coluna. # a mesma lógica pode ser seguida para outras linhas
print(l_coluna_1)


[[5 6]
 [6 1]
 [7 4]]
---
[5 6]
---
[5 6 7]


In [21]:
# adição e multiplicação de matrizes, divisão e outras funções
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
soma = n + o
print(soma)
print('----')
mult = n * o
print(mult)
print('----')
# funciona mesmo com matrizes de formatos diferentes

[[2 3]
 [4 5]]
----
[[1 2]
 [3 4]]
----


In [22]:
# fazendo transposição 
f = np.arange(15).reshape((3, 5))
print(f)
s = f.T
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
# outra forma de fazer transposição
s = np.transpose(f)
print(s)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [25]:
# expressões lógicas
v = np.random.randn(4, 4)
print(v)
print('---')
x = (v > 0) # realiza a verificação e devolve em True or False
print(x)
print('---')
z = np.where(v > 0, 1, -1) # faz a mesma coisa que no x, porém ele retorna o valor que eu defini.
print(z)

[[-1.32163838  0.39997209  0.92766514 -0.97497571]
 [ 0.93858649  0.28595336 -0.99887958 -1.54892303]
 [ 0.08564162  1.87399702 -1.83772542  0.56707589]
 [-0.60741462  0.82487552  0.03640248  0.30544795]]
---
[[False  True  True False]
 [ True  True False False]
 [ True  True False  True]
 [False  True  True  True]]
---
[[-1  1  1 -1]
 [ 1  1 -1 -1]
 [ 1  1 -1  1]
 [-1  1  1  1]]
